spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:lock;LOCK_TIMEOUT=10000
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false